/// 
Class ELFT.TIE.Rule.JACToRIOADTRule Extends Ens.Rule.Definition
{

Parameter RuleAssistClass = "EnsLib.HL7.MsgRouter.RuleAssist";

XData RuleDefinition [ XMLNamespace = "http://www.intersystems.com/rule" ]
{
<ruleDefinition alias="" context="EnsLib.HL7.MsgRouter.RoutingEngine" production="ELFT.TIE.Production.DevProduction">
<ruleSet name="JAC TO RIO ADT" effectiveBegin="" effectiveEnd="">
<rule name="ADT" disabled="false">

</rule>
</ruleSet>
</ruleDefinition>
}

}
